#!/bin/execlineb -P

# Set the system clock to something sensible,
# to get coherent logs until the initial NTP exchange

if { s6-clock @400000005a58000000000000 }


# Initialize the service manager

if { s6-rc-init /run/service }


# Run the service manager.
# Call it twice because the first time may spuriously "timeout"
# due to the clock jumping forward.

if -nt { s6-rc -t 600000 -- change ok-all }
s6-rc -t 600000 -- change ok-all
